// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/articles/[id].tsx";
import * as $3 from "./routes/articles/[id]/edit.tsx";
import * as $4 from "./routes/articles/create.tsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/ArticleTag.tsx";
import * as $$1 from "./islands/ContentForm.tsx";
import * as $$2 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/articles/[id].tsx": $2,
    "./routes/articles/[id]/edit.tsx": $3,
    "./routes/articles/create.tsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/ArticleTag.tsx": $$0,
    "./islands/ContentForm.tsx": $$1,
    "./islands/Counter.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
